spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    format_sql: true

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: student.log

address:
  service:
    url: http://localhost:8081/api/address